# Generated by Django 5.2 on 2025-05-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='payment',
            new_name='payments',
        ),
    ]
