name: Deploy to Server

on:
  push:
    branches:
      - main  # faqat main branchga push bo'lsa, ishga tushadi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Connect to Server and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/polya
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          systemctl restart apache2
